# A single CI script with github workflow
name: Tests

on:
  workflow_dispatch:
  push:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]
    uses: qiboteam/workflows/.github/workflows/rules-poetry.yml@main
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
      doctests: ${{ matrix.os == 'ubuntu-latest'}}
      poetry-extras: "--with docs,tests,analysis --all-extras"
    secrets: inherit
